#!/bin/bash
# Setdisplays - Change Monitor Layout predefined arrangment.
# Version 0.2

# TODO: Needs to handle rotation, and rotation of the wacom devices... This just got hard. ;)


case "$1" in
  default)   secondaries='--output HDMI1  --off  --output HDMI2 --off --output VIRTUAL1 --off'  ;;
  reading)   primary='--output eDP1 --auto --primary --rotate left'       ;;
#  vgaabove)  secondaries='--output VGA-0  --auto --above LVDS'           ;;
#  hdmiabove) secondaries='--output HDMI-0 --auto --above LVDS'           ;;
#  rightof)   secondaries='--output VGA-0  --auto --right-of LVDS'        ;;
#  leftof)    secondaries='--output HDMI-0 --auto --left-of LVDS'         ;;
#  hdtv)      secondaries='--output HDMI-0 --auto'                        ;;
#  justhdmi)  primary='--output eDP1 --off'\
#             secondaries='--output VGA-0  --off  --output HDMI-0 --auto' ;;
  *)
    echo "Usage: $0 PROFILE"
    exit 1
esac

${SETDISPLAYS_DBG:+echo} xrandr ${primary:---output eDP1 --auto --primary --rotate normal}  $secondaries
